AWSTemplateFormatVersion: 2010-09-09

Description: |
  This is the web server for the kittens static website.  Creates an
  EC2 instance with user data installing httpd and git

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the key-pair for the web server

  MySecurityGroup:
    Description: My security group for the app
    Type: AWS::EC2::SecurityGroup::GroupName

Resources:
  KittensWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e731c8a588258d0d
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: aws-project-01
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf update -y
          dnf install git httpd -y
          cd /home/ec2-user
          git clone https://github.com/SeattleSlough/Clarusway-AWS-Project-01.git app
          cp /home/ec2-user/app/static-web/* /var/www/html
          systemctl start httpd
          systemctl enable httpd

Outputs:
  PublicIPAddress:
    Description: The public IP of my instance
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt KittensWebServer.PublicIp
  # LogicalID: type 'ouput' to generate template
  #   Description:
  #   Value:
  #   Export:
  #     Name: